version: '3.1'
services:
  # Laravel app
  app_prod:
    build:
      context: ./
      dockerfile: app.dockerfile
    environment:
      # for dev only
      # allows for file changes to be detected
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    image: groundctrl_app_prod
    working_dir: /var/www
    volumes:
      - .:/var/www
  # nginx proxy server
  web_prod:
    build:
      context: ./
      dockerfile: web-prod.dockerfile
    image: groundctrl_web_prod
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8080:80
  # postgres database
  postgres_prod:
    build:
      context: ./
      dockerfile: postgres-prod.dockerfile
    image: groundctrl_db_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: groundctrl
    volumes:
      - groundctrl_db_prod:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  groundctrl_db_prod:
